### ISSUE TITLE
Some errors converting openfmri to BIDS format

### ISSUE THREAD

**Issue by dohmatob** [INCF/openfmri2bids#15]
Convert has some failures:

Description
===

**Error: 1**

Repetition time did not match between the scan's header and the associated JSON metadata file.48 files

**Reason:**
Repetition time defined in the JSON (2 sec.) did not match the one defined in the NIFTI header (1 sec.)

**Error: 2**

sform_code and qform_code in the image header are 0. The image/file will be considered invalid or assumed to be in LAS orientation.

Possible Fix
=======
The error occurs because the TR value specified in the `scan_key.txt` is incorrect (i.e different with what's specified in the image header). 
- Fix: `tr = image_header["pixdim"][4]`

**Comment by chrisgorgo** [comment]
This seems like a problem with the dataset not the converter...

**Comment by dohmatob** [comment]
OK, fair enough. closing.
