### ISSUE TITLE
Add option to move / symbolically link nii files

### ISSUE THREAD

**Issue by bcipolli** [INCF/openfmri2bids#3]
Rather than an `empty_nii` parameter, it would be great to allow the following options:
- Copy nii files
- Move nii files
- Create a symbolic to nii files.

Or, just pass a generic function that accepts a `src_path` and `dest_path`, and let the user do it themselves.

If you let me know tonight a good way to go, I might even code this myself! ;)

**Comment by chrisgorgo** [comment]
That's a great idea, but I can't implemented it right now (on vacation). Go for it!

**Comment by bcipolli** [comment]
Cool, got the base version working on my machine (move/copy/link/empty). Will open a PR later today.
